"""
schema.py — canonical normalized MBO schema and shared constants.

This module is the single source of truth for the provider-neutral event
contract consumed by validation, reconstruction, research features and future
trading code.

Design rules:
    - prices are fixed-point int64 at scale 1e9;
    - provider/control flags preserve Databento-compatible bit assignments;
    - normalization provenance is carried separately in norm_flags;
    - sequence preserves provider sequence, subsequence orders normalized rows
      deterministically inside one provider sequence.
"""

from __future__ import annotations

from enum import IntFlag
from pathlib import Path
from typing import Final

import pyarrow as pa


# ---------------------------------------------------------------------------
# PRICE CONSTANTS
# ---------------------------------------------------------------------------

FIXED_PRICE_SCALE: Final[int] = 1_000_000_000
UNDEF_PRICE: Final[int] = 9_223_372_036_854_775_807


# ---------------------------------------------------------------------------
# PROVIDER / CONTROL FLAGS
# ---------------------------------------------------------------------------

class Flags(IntFlag):
    """Canonical provider/control flags.

    Bit assignments intentionally follow Databento's record flags. Internal
    normalization state must never reuse these bits; use NormFlags instead.
    """

    F_LAST               = 0x80
    F_TOB                = 0x40
    F_SNAPSHOT           = 0x20
    F_MBP                = 0x10
    F_BAD_TS_RECV        = 0x08
    F_MAYBE_BAD_BOOK     = 0x04
    F_PUBLISHER_SPECIFIC = 0x02
    # 0x01 is intentionally left unassigned by the canonical contract.


class NormFlags(IntFlag):
    """Normalization/provenance flags generated by Destiny.

    These flags describe how a canonical row was produced. They are orthogonal
    to exchange/provider control flags and therefore live in a separate uint16
    column.
    """

    NONE                 = 0x0000
    N_SYNTHETIC          = 0x0001
    N_REPAIRED           = 0x0002
    N_COARSE_TS          = 0x0004
    N_VALIDATION_ANOMALY = 0x0008
    N_INFERRED_SIDE      = 0x0010
    N_INFERRED_SIZE      = 0x0020


# ---------------------------------------------------------------------------
# ACTION / SIDE ENUMS
# ---------------------------------------------------------------------------

class Action:
    """Provider-neutral MBO action names."""

    ADD    : Final[str] = "ADD"
    CANCEL : Final[str] = "CANCEL"
    MODIFY : Final[str] = "MODIFY"
    CLEAR  : Final[str] = "CLEAR"
    TRADE  : Final[str] = "TRADE"
    FILL   : Final[str] = "FILL"
    NONE   : Final[str] = "NONE"

    BOOK_ACTIONS : Final[frozenset[str]] = frozenset({ADD, CANCEL, MODIFY, CLEAR})
    ORDER_ID_REQUIRED : Final[frozenset[str]] = frozenset({ADD, CANCEL, MODIFY})
    PRICE_REQUIRED : Final[frozenset[str]] = frozenset({ADD, MODIFY})
    SIZE_REQUIRED : Final[frozenset[str]] = frozenset({ADD, MODIFY})

    DATABENTO_MAP : Final[dict[str, str]] = {
        "A": ADD,
        "C": CANCEL,
        "M": MODIFY,
        "R": CLEAR,
        "T": TRADE,
        "F": FILL,
        "N": NONE,
    }


class Side:
    """Provider-neutral side names with action-dependent semantics."""

    BID  : Final[str] = "BID"
    ASK  : Final[str] = "ASK"
    NONE : Final[str] = "NONE"

    ORDER_SIDES : Final[frozenset[str]] = frozenset({BID, ASK})

    DATABENTO_MAP : Final[dict[str, str]] = {
        "B": BID,
        "A": ASK,
        "N": NONE,
    }


# ---------------------------------------------------------------------------
# ARROW SCHEMAS
# ---------------------------------------------------------------------------

_DICT_INT8_STR  = pa.dictionary(pa.int8(), pa.string())
_DICT_INT16_STR = pa.dictionary(pa.int16(), pa.string())

NORMALIZED_MBO_SCHEMA: Final[pa.Schema] = pa.schema([
    pa.field("ts_event",      pa.uint64(),       nullable=False),
    pa.field("ts_recv",       pa.uint64(),       nullable=False),
    pa.field("venue",         _DICT_INT8_STR,    nullable=False),
    pa.field("product",       _DICT_INT8_STR,    nullable=False),
    pa.field("contract",      _DICT_INT16_STR,   nullable=False),
    pa.field("action",        _DICT_INT8_STR,    nullable=False),
    pa.field("side",          _DICT_INT8_STR,    nullable=False),
    pa.field("price",         pa.int64(),        nullable=False),
    pa.field("size",          pa.uint32(),       nullable=False),
    pa.field("order_id",      pa.uint64(),       nullable=False),
    pa.field("flags",         pa.uint8(),        nullable=False),
    pa.field("norm_flags",    pa.uint16(),       nullable=False),
    pa.field("sequence",      pa.uint32(),       nullable=False),
    pa.field("subsequence",   pa.uint16(),       nullable=False),
    pa.field("publisher_id",  pa.uint16(),       nullable=False),
    pa.field("instrument_id", pa.uint32(),       nullable=False),
])

REJECTED_EVENTS_SCHEMA: Final[pa.Schema] = pa.schema([
    pa.field("ts_event",      pa.uint64(),       nullable=False),
    pa.field("ts_recv",       pa.uint64(),       nullable=False),
    pa.field("venue",         _DICT_INT8_STR,    nullable=False),
    pa.field("product",       _DICT_INT8_STR,    nullable=False),
    pa.field("contract",      _DICT_INT16_STR,   nullable=False),
    pa.field("action",        _DICT_INT8_STR,    nullable=True),
    pa.field("side",          _DICT_INT8_STR,    nullable=True),
    pa.field("price",         pa.int64(),        nullable=True),
    pa.field("size",          pa.uint32(),       nullable=True),
    pa.field("order_id",      pa.uint64(),       nullable=True),
    pa.field("flags",         pa.uint8(),        nullable=True),
    pa.field("norm_flags",    pa.uint16(),       nullable=True),
    pa.field("sequence",      pa.uint32(),       nullable=True),
    pa.field("subsequence",   pa.uint16(),       nullable=True),
    pa.field("publisher_id",  pa.uint16(),       nullable=True),
    pa.field("instrument_id", pa.uint32(),       nullable=True),
    pa.field("reject_reason", pa.string(),       nullable=False),
    pa.field("mode",          pa.string(),       nullable=False),
])


# ---------------------------------------------------------------------------
# VALIDATION MODES
# ---------------------------------------------------------------------------

class ValidationMode:
    """Validation policy applied after provider normalization.

    STRICT drops anomalous events from canonical output while persisting the
    rejected audit row. LOOSE persists the audit row and keeps the event with
    NormFlags.N_VALIDATION_ANOMALY set.
    """

    STRICT : Final[str] = "STRICT"
    LOOSE  : Final[str] = "LOOSE"


# ---------------------------------------------------------------------------
# PATH HELPERS
# ---------------------------------------------------------------------------

def normalized_path(
    base_dir: Path,
    provider: str,
    venue: str,
    product: str,
    contract: str,
    year: int,
    month: int,
    date_str: str,
    suffix: str = "mbo",
) -> Path:
    """Build the canonical normalized Parquet path."""
    return (
        base_dir
        / f"provider={provider}"
        / f"venue={venue}"
        / f"product={product}"
        / f"contract={contract}"
        / f"year={year}"
        / f"month={month:02d}"
        / f"{contract}_{date_str}_{suffix}.parquet"
    )


def reconstructed_path(
    base_dir: Path,
    provider: str,
    venue: str,
    product: str,
    contract: str,
    year: int,
    month: int,
    date_str: str,
    schema: str,
) -> Path:
    """Build the canonical reconstructed Parquet path."""
    return (
        base_dir
        / f"provider={provider}"
        / f"venue={venue}"
        / f"product={product}"
        / f"contract={contract}"
        / f"year={year}"
        / f"month={month:02d}"
        / f"{contract}_{date_str}_{schema}.parquet"
    )


def rejected_path(
    base_dir: Path,
    provider: str,
    venue: str,
    product: str,
    contract: str,
    year: int,
    month: int,
    date_str: str,
) -> Path:
    """Build the per-session rejected-event audit path."""
    return (
        base_dir
        / f"provider={provider}"
        / f"venue={venue}"
        / f"product={product}"
        / f"contract={contract}"
        / f"year={year}"
        / f"month={month:02d}"
        / f"{contract}_{date_str}_rejected.parquet"
    )
