"""Compare current data outputs with a previously captured safety-net manifest.

This is a read-only differential check. Any semantic SHA change is reported as
an unexpected regression until the corresponding R0 design decision explicitly
approves it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_REPO_ROOT / "tests" / "regression"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from shared.fingerprint import semantic_parquet_fingerprint  # noqa: E402
from shared.metrics_mbo import mbo_path, rejected_path        # noqa: E402
from shared.metrics_mbp1 import mbp1_path                    # noqa: E402


_GREEN = "\033[92m"
_RED = "\033[91m"
_YELLOW = "\033[93m"
_RESET = "\033[0m"


def _resolve_path(section: str, product: str, payload: dict, kind: str) -> Path:
    contract = payload["contract"]
    date_str = payload["date"]
    if section == "normalization" and kind == "mbo":
        return mbo_path(product, contract, date_str)
    if section == "normalization" and kind == "rejected":
        return rejected_path(product, contract, date_str)
    if section == "reconstruction" and kind == "mbp1":
        return mbp1_path(product, contract, date_str)
    raise ValueError(f"Unsupported manifest entry: {section}/{kind}")


def _compare_file(path: Path, expected: dict) -> list[str]:
    failures: list[str] = []
    expected_exists = bool(expected.get("exists"))

    if not path.exists():
        if expected_exists:
            failures.append("file is now missing")
        return failures

    if not expected_exists:
        failures.append("file now exists but baseline recorded it as missing")
        return failures

    current = semantic_parquet_fingerprint(path)
    for key in ("row_count", "semantic_sha256", "schema"):
        if current.get(key) != expected.get(key):
            failures.append(
                f"{key}: expected={expected.get(key)!r} current={current.get(key)!r}"
            )
    return failures


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check current outputs against a deep R0 manifest.")
    parser.add_argument("manifest", type=Path, help="Manifest generated by capture_baseline.py")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    manifest = json.loads(args.manifest.read_text())

    total = 0
    failed = 0

    for section in ("normalization", "reconstruction"):
        print(f"\n{section.upper()}")
        for product, payload in manifest.get(section, {}).items():
            for kind, expected in payload.items():
                if kind in {"contract", "date"}:
                    continue
                total += 1
                path = _resolve_path(section, product, payload, kind)
                failures = _compare_file(path, expected)
                label = f"{product:<5} {payload['contract']:<14} {payload['date']} {kind}"
                if failures:
                    failed += 1
                    print(f"{_RED}[FAIL]{_RESET} {label}")
                    for failure in failures:
                        print(f"       - {failure}")
                else:
                    print(f"{_GREEN}[PASS]{_RESET} {label}")

    if failed:
        print(f"\n{_RED}FAILED: {failed}/{total} output fingerprints changed.{_RESET}")
        print("Every diff must be classified as EXPECTED CHANGE or REGRESSION before merge.")
        return 1

    if total == 0:
        print(f"{_YELLOW}No manifest entries were checked.{_RESET}")
        return 2

    print(f"\n{_GREEN}PASSED: {total}/{total} deep fingerprints match baseline.{_RESET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
